version: "1"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - .:/database
    environment:
      MYSQL_ROOT_PASSWORD: "movie123" 
  

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/webapp
    